[package]
name = "day-12"
version = "0.1.0"
authors = ["Louis Dufeu <louis.dufeu@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
